// lib/blogData.ts

export type BlogPost = {
  slug: string;
  title: string;
  date: string; // ISO yyyy-mm-dd
  tags: string[];
  excerpt?: string;
  content?: string; // Paste full article content here (plain text). You can add basic <p> tags if you like.
};

// Helper: nice date on UI
export function formatDate(d: string) {
  return new Date(d).toLocaleDateString("en-GB", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

// NOTE: Dates are spaced weekly on Mondays across Oct–Dec 2025
// You can adjust any date string if you prefer.
export const posts: BlogPost[] = [
  {
    slug: "why-communication-is-key-to-relationship-success",
    title: "Why Communication is Key to Relationship Success",
    date: "2025-10-06",
    tags: ["Relationships", "Communication", "Counselling"],
    excerpt:
      "Open, honest dialogue builds trust, prevents assumptions, and nurtures long-term connection.",
    content: ``,
  },
  {
    slug: "why-mental-health-should-be-a-priority-in-your-daily-life",
    title: "Why Mental Health Should Be a Priority in Your Daily Life",
    date: "2025-10-13",
    tags: ["Mental Health", "Self-Care", "Wellbeing"],
    excerpt:
      "Practical steps to protect your mind, reduce stress, and improve daily functioning.",
    content: ``,
  },
  {
    slug: "balancing-independence-and-togetherness-in-relationships",
    title: "Balancing Independence and Togetherness in Relationships",
    date: "2025-10-20",
    tags: ["Relationships", "Boundaries", "Attachment"],
    excerpt:
      "How to honour your individuality while staying emotionally connected.",
    content: ``,
  },
  {
    slug: "breaking-the-stigma",
    title: "Breaking the Stigma",
    date: "2025-10-27",
    tags: ["Mental Health", "Therapy", "Awareness"],
    excerpt: "Normalising help-seeking and compassionate care.",
    content: ``,
  },
  {
    slug: "building-emotional-resilience-how-to-thrive-in-challenging-times",
    title: "Building Emotional Resilience: How to Thrive in Challenging Times",
    date: "2025-11-03",
    tags: ["Resilience", "Stress", "Coping"],
    excerpt: "Resilience is a trainable skill — here’s how to grow it.",
    content: ``,
  },
  {
    slug: "building-healthy-relationships",
    title: "Building Healthy Relationships",
    date: "2025-11-10",
    tags: ["Relationships", "Communication", "Trust"],
    excerpt: "The everyday habits that make relationships work.",
    content: ``,
  },
  {
    slug: "building-resilience-in-difficult-times",
    title: "Building Resilience in Difficult Times",
    date: "2025-11-17",
    tags: ["Resilience", "Coping", "Stress"],
    excerpt: "Staying steady when life isn’t.",
    content: ``,
  },
  {
    slug: "building-stronger-relationships-through-communication",
    title: "Building Stronger Relationships Through Communication",
    date: "2025-11-24",
    tags: ["Communication", "Couples", "Relationships"],
    excerpt: "Move from criticism and defensiveness to clarity and care.",
    content: ``,
  },
  {
    slug: "building-trust-in-relationships",
    title: "Building Trust in Relationships",
    date: "2025-12-01",
    tags: ["Trust", "Repair", "Attachment"],
    excerpt: "Trust is built in small moments over time.",
    content: ``,
  },
  {
    slug: "coping-with-anxiety",
    title: "Coping with Anxiety",
    date: "2025-12-08",
    tags: ["Anxiety", "Self-Care", "Coping"],
    excerpt: "Evidence-based tools to reduce anxious spirals.",
    content: ``,
  },
  {
    slug: "coping-with-relationship-stress",
    title: "Coping with Relationship Stress",
    date: "2025-12-15",
    tags: ["Relationships", "Stress", "Conflict"],
    excerpt: "How to de-escalate and reconnect.",
    content: ``,
  },
  {
    slug: "effective-communication-techniques-for-couples",
    title: "Effective Communication Techniques for Couples",
    date: "2025-12-22",
    tags: ["Couples", "Communication", "Skills"],
    excerpt: "Specific scripts and skills you can use today.",
    content: ``,
  },
  {
    slug: "how-to-build-a-strong-foundation-in-your-relationship",
    title: "How to Build a Strong Foundation in Your Relationship",
    date: "2025-12-29",
    tags: ["Relationships", "Habits", "Prevention"],
    excerpt: "Lay the groundwork for long-term stability.",
    content: ``,
  },
  {
    slug: "how-to-build-healthy-communication-in-relationships",
    title: "How to Build Healthy Communication in Relationships",
    date: "2026-01-05",
    tags: ["Communication", "Empathy", "Listening"],
    excerpt: "From reactive to reflective — a communication upgrade.",
    content: ``,
  },
  {
    slug: "how-to-cope-with-anxiety-in-relationships",
    title: "How to Cope with Anxiety in Relationships",
    date: "2026-01-12",
    tags: ["Anxiety", "Attachment", "Soothing"],
    excerpt: "Balance reassurance with self-regulation.",
    content: ``,
  },
  {
    slug: "how-to-create-healthy-boundaries-in-relationships",
    title: "How to Create Healthy Boundaries in Relationships",
    date: "2026-01-19",
    tags: ["Boundaries", "Self-Respect", "Values"],
    excerpt: "Boundaries protect the relationship — and you.",
    content: ``,
  },
  {
    slug: "how-to-cultivate-mindfulness-in-a-busy-world",
    title: "How to Cultivate Mindfulness in a Busy World",
    date: "2026-01-26",
    tags: ["Mindfulness", "Self-Care", "Calm"],
    excerpt: "Small practices, big effect.",
    content: ``,
  },
  {
    slug: "how-to-manage-anxiety-in-your-everyday-life",
    title: "How to Manage Anxiety in Your Everyday Life",
    date: "2026-02-02",
    tags: ["Anxiety", "Lifestyle", "CBT"],
    excerpt: "Daily routines that dial anxiety down.",
    content: ``,
  },
  {
    slug: "how-to-manage-stress-in-relationships",
    title: "How to Manage Stress in Relationships",
    date: "2026-02-09",
    tags: ["Stress", "Couples", "Support"],
    excerpt: "Stress-proof your partnership.",
    content: ``,
  },
  {
    slug: "how-to-strengthen-communication-in-relationships",
    title: "How to Strengthen Communication in Relationships",
    date: "2026-02-16",
    tags: ["Communication", "Conflict", "Repair"],
    excerpt: "More understanding, less arguing.",
    content: ``,
  },
  {
    slug: "improving-communication-in-relationships",
    title: "Improving Communication in Relationships",
    date: "2026-02-23",
    tags: ["Communication", "Couples"],
    excerpt: "Practical steps you can practice tonight.",
    content: ``,
  },
  {
    slug: "managing-stress-and-maintaining-balance-in-a-relationship",
    title: "Managing Stress and Maintaining Balance in a Relationship",
    date: "2026-03-02",
    tags: ["Stress", "Balance", "Wellbeing"],
    excerpt: "Protect connection during busy seasons.",
    content: ``,
  },
  {
    slug: "managing-stress-effective-techniques-for-everyday-life",
    title: "Managing Stress: Effective Techniques for Everyday Life",
    date: "2026-03-09",
    tags: ["Stress", "Coping", "Lifestyle"],
    excerpt: "Reduce overwhelm with simple habits.",
    content: ``,
  },
  {
    slug: "overcoming-perfectionism",
    title: "Overcoming Perfectionism",
    date: "2026-03-16",
    tags: ["Perfectionism", "Self-Compassion", "CBT"],
    excerpt: "Let go of impossible standards.",
    content: ``,
  },
  {
    slug: "overcoming-relationship-challenges",
    title: "Overcoming Relationship Challenges",
    date: "2026-03-23",
    tags: ["Repair", "Conflict", "Couples"],
    excerpt: "From rupture to repair.",
    content: ``,
  },
  {
    slug: "recognising-and-addressing-burnout-in-everyday-life",
    title: "Recognising and Addressing Burnout in Everyday Life",
    date: "2026-03-30",
    tags: ["Burnout", "Work", "Recovery"],
    excerpt: "Burnout isn’t just tiredness — here’s how to heal.",
    content: ``,
  },
  {
    slug: "recognising-and-breaking-the-cycle-of-codependency",
    title: "Recognising and Breaking the Cycle of Codependency",
    date: "2026-04-06",
    tags: ["Boundaries", "Codependency", "Self-Worth"],
    excerpt: "Untangle the patterns that keep you stuck.",
    content: ``,
  },
  {
    slug: "setting-boundaries-in-relationships",
    title: "Setting Boundaries in Relationships",
    date: "2026-04-13",
    tags: ["Boundaries", "Respect", "Safety"],
    excerpt: "Say yes to yourself without losing connection.",
    content: ``,
  },
  {
    slug: "simple-self-care",
    title: "Simple Self-Care",
    date: "2026-04-20",
    tags: ["Self-Care", "Habits", "Wellbeing"],
    excerpt: "Micro-practices that add up.",
    content: ``,
  },
  {
    slug: "the-importance-of-setting-boundaries-in-relationships",
    title: "The Importance of Setting Boundaries in Relationships",
    date: "2026-04-27",
    tags: ["Boundaries", "Relationships", "Communication"],
    excerpt: "Boundaries as an act of love.",
    content: ``,
  },
  {
    slug: "the-power-of-self-care",
    title: "The Power of Self-Care",
    date: "2026-05-04",
    tags: ["Self-Care", "Mental Health"],
    excerpt: "Care for yourself to care for others well.",
    content: ``,
  },
  {
    slug: "the-role-of-self-awareness",
    title: "The Role of Self-Awareness",
    date: "2026-05-11",
    tags: ["Awareness", "Growth", "Mindfulness"],
    excerpt: "Know yourself, change your patterns.",
    content: ``,
  },
  {
    slug: "the-role-of-self-care",
    title: "The Role of Self-Care",
    date: "2026-05-18",
    tags: ["Self-Care", "Lifestyle"],
    excerpt: "A sustainable plan that fits your life.",
    content: ``,
  },
  {
    slug: "the-role-of-therapy-in-improving-mental-health",
    title: "The Role of Therapy in Improving Mental Health",
    date: "2026-05-25",
    tags: ["Therapy", "Counselling", "Mental Health"],
    excerpt: "What therapy is (and isn’t).",
    content: ``,
  },
  {
    slug: "the-role-of-trust-in-a-healthy-relationship",
    title: "The Role of Trust in a Healthy Relationship",
    date: "2026-06-01",
    tags: ["Trust", "Relationships"],
    excerpt: "Consistent care builds safety.",
    content: ``,
  },
  {
    slug: "the-role-of-vulnerability-in-building-trust-in-relationships",
    title: "The Role of Vulnerability in Building Trust in Relationships",
    date: "2026-06-08",
    tags: ["Vulnerability", "Trust", "Intimacy"],
    excerpt: "Courage to be known creates closeness.",
    content: ``,
  },
  {
    slug: "the-role-of-vulnerability-in-strengthening-relationships",
    title: "The Role of Vulnerability in Strengthening Relationships",
    date: "2026-06-15",
    tags: ["Vulnerability", "Connection"],
    excerpt: "Soft fronts, strong backs.",
    content: ``,
  },
  {
    slug: "understanding-ptsd",
    title: "Understanding PTSD",
    date: "2026-06-22",
    tags: ["Trauma", "PTSD", "Recovery"],
    excerpt: "Gentle education and support pathways.",
    content: ``,
  },
  {
    slug: "understanding-the-connection-between-mental-and-physical-health",
    title: "Understanding the Connection Between Mental Health and Physical Health",
    date: "2026-06-29",
    tags: ["Mind-Body", "Lifestyle", "Wellbeing"],
    excerpt: "Your body keeps the score — and the solution.",
    content: ``,
  },
  {
    slug: "understanding-the-importance-of-emotional-intimacy-in-relationships",
    title: "Understanding the Importance of Emotional Intimacy in Relationships",
    date: "2026-07-06",
    tags: ["Intimacy", "Attachment", "Couples"],
    excerpt: "Emotional closeness is built, not found.",
    content: ``,
  },
];
